=== AbrahamFB/Dise-o-de-la-Interacci-n/21092020/librero.dtd
<!DOCTYPE librero
[
<!ELEMENT librero (libro)*>
<!ELEMENT libro (titulo,autor*,editorial)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT autor (#PCDATA)>
<!ELEMENT editorial (#PCDATA)>
]>

=== AbrahamFB/Dise-o-de-la-Interacci-n/21092020/lbrero.xml
<?xml version="1.0" encoding="UTF-8">
<!DOCTYPE librero SYSTEM "librero.dtd">
<?xml-stylesheet href="librero.css" type="text/css"?>
<librero>
  <libro>
    <titulo>fundamento de base de datos</titulo>
    <autor>Korth</autor>
    <autor>sudersarahi</autor>
    <editorial>Mc Graw Hill</editorial>
  </libro>
  <libro>
    <titulo>matemáticas básicas</titulo>
    <editorial>pearson</editorial>
</librero>
